# This is a basic workflow to help you get started with Actions

name: Target Multiple Node.js Versions and Operating Systems
on: [push]

jobs:
  build:
    name: Run TestCafe Tests
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        node: [8, 10, 12]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            args: "chrome tests"